config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :subs, except: :destroy
  resources :posts, except: [:index, :destroy]

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :text
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  #TODO: Consider validating :post_subs
  # validates :post_subs, presence: true

  belongs_to :author,
    class_name: :User

  has_many :post_subs

  has_many :subs, dependent: :destroy,
    through: :post_subs,
    source: :sub
end

app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ActiveRecord::Base
  validates :post_id, :sub_id, presence: true
  validates_uniqueness_of :post_id, scope: :sub_id
  
  belongs_to :post

  belongs_to :sub
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator,
    class_name: 'User'

  has_many :post_subs

  has_many :posts, dependent: :destroy,
    through: :post_subs,
    source: :post

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password

  after_initialize :ensure_session_token

  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 8, allow_nil: true}

  has_many :moderated_subs, dependent: :destroy,
    class_name: 'Sub',
    foreign_key: :moderator_id

  has_many :authored_posts, dependent: :destroy,
    class_name: 'Post',
    foreign_key: :author_id

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    render json: @post
  end

  def new
    render :new
  end

  def create
    post = Post.new(post_params)
    if post.save
      redirect_to post_url
    else
      redirect_to new_post_url
    end
  end

  def edit
    @post = Post.find(params[:id])
    if allow_to_edit?(@post)
      render :edit
    else
      redirect_to post_url
    end

  end

  def update
    post = Post.find(params[:id])
    if allow_to_edit?(post) && post.update
      redirect_to post_url
    else
      redirect_to edit_post_url
    end
  end

  private
  def post_params
    params.require(:post).permit(:title,
                                 :url,
                                 :content,
                                 :sub_ids = [],
                                 :author_id)
  end

  def allow_to_edit?(post)
    return false unless post && current_user
    current_user.id == post.author_id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    username, password = session_params.values
    user = User.find_by(username: username)
    if user
      log_in!(user)
      #TODO: redirect somewhere
      render text: "success"
    else
      redirect_to new_session_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  private
  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def index
    @subs = Sub.all
    render json: @subs
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render json: @sub
  end

  def new
    render :new
  end

  def create
    new_sub = Sub.new(sub_params)
    if new_sub.save
      redirect_to sub_url(new_sub)
    else
      redirect_to new_sub_url
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    found_sub = Sub.find(params[:id])
    if found_sub && found_sub.update(sub_params)
      redirect_to sub_url(found_sub)
    else
      redirect_to edit_sub_url
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in!(user)
      #TODO: Redirect somewhere
      render text: "success"
    else
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%if current_user%>
  <%= button_to 'log out', session_url, method: :delete %>
<% else %>
  <%= button_to 'log in', new_session_url, method: :get%>
  <%= button_to 'sign up', new_user_url, method: :get%>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_shared_form.html.erb
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= render "shared/auth_token" %>
  <div>
    <label for="post[title]">Title: </label>
    <input type="text" name="post[title]" value="<%= post_title %>">
  </div>
  <div>
    <label for="post[url]">URL: </label>
    <input type="text" name="post[url]" value="<%= post_url %>">
  </div>
  <div>
    <label for="post[content]">Content: </label>
    <input type="text" name="post[content]" value="<%= post_content %>">
  </div>
  <div>
    <label for="post[sub_id]">Sub (id): </label>
      <input type="text" name="post[sub_id]" value="<%= post_sub %>">
    </div>
  </div>
  <div>
    <label for="post[author_id]">Author (id): </label>
      <input type="text" name="post[author_id]" value="<%= post_author %>">
    </div>
  </div>
  <%= button_to "Submit", action, method: method %>
</form>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>

<%= render "shared_form", action: posts_url,
                          method: "patch",
                          post_title: @post.title,
                          post_url: @post.url,
                          post_content: @post.content,
                          post_sub: @post.sub_id,
                          post_author: @post.author_id %>

app/views/posts/new.html.erb
<h1> New Post </h1>

<%= render "shared_form", action: posts_url,
                          method: "post",
                          post_title: "",
                          post_url: "",
                          post_content: "",
                          post_sub: "",
                          post_author: "" %>

app/views/shared/_auth_token.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

app/views/subs/edit.html.erb
<h1> Edit <%= @sub.title %> </h1>

<%= render "shared_form", action: sub_url,
                          method: "patch",
                          sub_title: @sub.title,
                          sub_description: @sub.description,
                          sub_moderator: @sub.moderator_id %>

app/views/subs/new.html.erb
<h1> New Sub </h1>

<%= render "shared_form", action: subs_url,
                          method: "post",
                          sub_title: "",
                          sub_description: "",
                          sub_moderator: "" %>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="_method" value="post">
  <%= render "shared/auth_token" %>
  <div>
    <label for="user[username]">Username: </label>
    <input type="text" name="user[username]">
  </div>
  <div>
    <label for="user[password]">Password: </label>
    <input type="password" name="user[password]">
  </div>
  <%= button_to 'Sign Up' %>
</form>